// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: Desktop_Effect_28_24

#ifndef _DESKTOP_EFFECT_28_24_UI_H
#define _DESKTOP_EFFECT_28_24_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Title1;
extern lv_obj_t * ui_TimeImage;
extern lv_obj_t * ui_DateImage;
extern lv_obj_t * ui_TimeLabel;
extern lv_obj_t * ui_DateLabel;
extern lv_obj_t * ui_LocalImage;
extern lv_obj_t * ui_LocalLabel;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Title2;
extern lv_obj_t * ui_WeatherImage;
extern lv_obj_t * ui_WeatherLabel;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_TempImage;
extern lv_obj_t * ui_HumiImage;
extern lv_obj_t * ui_WindImage;
extern lv_obj_t * ui_TempLabel;
extern lv_obj_t * ui_WindLabel;
extern lv_obj_t * ui_HumiLabel;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Title3;
extern lv_obj_t * ui_MusicImage;
void ui_event_PlayOrPauseButton(lv_event_t * e);
extern lv_obj_t * ui_PlayOrPauseButton;
extern lv_obj_t * ui_PlayOrPauseLabel;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_SongNameLabel;
extern lv_obj_t * ui_MusicStatusLabel;
void ui_event_NextButton(lv_event_t * e);
extern lv_obj_t * ui_NextButton;
void ui_event_PreviousButton(lv_event_t * e);
extern lv_obj_t * ui_PreviousButton;
// CUSTOM VARIABLES

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
void ui_event_Screen4(lv_event_t * e);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Title4;
extern lv_obj_t * ui_HourDropdown;
extern lv_obj_t * ui_MinDropdown;
extern lv_obj_t * ui_HourAlarm;
extern lv_obj_t * ui_MinAlarm;
void ui_event_ClockSwitch(lv_event_t * e);
extern lv_obj_t * ui_ClockSwitch;
// CUSTOM VARIABLES

// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
void ui_event_Screen5(lv_event_t * e);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Title5;
void ui_event_StartButton(lv_event_t * e);
extern lv_obj_t * ui_StartButton;
extern lv_obj_t * ui_StartLabel;
void ui_event_StopButton(lv_event_t * e);
extern lv_obj_t * ui_StopButton;
extern lv_obj_t * ui_StopLabel;
void ui_event_ClearButton(lv_event_t * e);
extern lv_obj_t * ui_ClearButton;
extern lv_obj_t * ui_ClearLabel;
extern lv_obj_t * ui_TimerLabel;
extern lv_obj_t * ui_Spinner1;
// CUSTOM VARIABLES

// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
void ui_event_Screen6(lv_event_t * e);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_Title6;
extern lv_obj_t * ui_OnImage;
extern lv_obj_t * ui_OffImage;
void ui_event_OnButton(lv_event_t * e);
extern lv_obj_t * ui_OnButton;
extern lv_obj_t * ui_Label11;
void ui_event_OffButton(lv_event_t * e);
extern lv_obj_t * ui_OffButton;
extern lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1_png);    // assets/1.png
LV_IMG_DECLARE(ui_img_1277292775);    // assets/桌面效果案例ui_11 副本 16.png
LV_IMG_DECLARE(ui_img_195563596);    // assets/桌面效果案例ui_11 副本 17.png
LV_IMG_DECLARE(ui_img_432210255);    // assets/桌面效果案例ui_11 副本 18.png
LV_IMG_DECLARE(ui_img_2_png);    // assets/2.png
LV_IMG_DECLARE(ui_img_1274435258);    // assets/太阳.png
LV_IMG_DECLARE(ui_img_854221414);    // assets/桌面效果案例ui_11 副本 24.png
LV_IMG_DECLARE(ui_img_1935950593);    // assets/桌面效果案例ui_11 副本 25.png
LV_IMG_DECLARE(ui_img_1277287524);    // assets/桌面效果案例ui_11 副本 26.png
LV_IMG_DECLARE(ui_img_3_png);    // assets/3.png
LV_IMG_DECLARE(ui_img_1763876406);    // assets/音乐盒.png
LV_IMG_DECLARE(ui_img_853450402);    // assets/下一首.png
LV_IMG_DECLARE(ui_img_862951715);    // assets/上一首.png
LV_IMG_DECLARE(ui_img_4_png);    // assets/4.png
LV_IMG_DECLARE(ui_img_5_png);    // assets/5.png
LV_IMG_DECLARE(ui_img_6_png);    // assets/6.png
LV_IMG_DECLARE(ui_img_126136084);    // assets/桌面效果案例ui_11 副本 31.png
LV_IMG_DECLARE(ui_img_955593095);    // assets/桌面效果案例ui_11 副本 30.png

// FONTS
LV_FONT_DECLARE(ui_font_Bodon28);
LV_FONT_DECLARE(ui_font_ItaBodon22);
LV_FONT_DECLARE(ui_font_ItaBodon16);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
