// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: Desktop_Effect_28_24

#include "ui.h"

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Title5 = lv_image_create(ui_Screen5);
    lv_image_set_src(ui_Title5, &ui_img_5_png);
    lv_obj_set_width(ui_Title5, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_Title5, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_Title5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Title5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Title5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_StartButton = lv_button_create(ui_Screen5);
    lv_obj_set_width(ui_StartButton, 65);
    lv_obj_set_height(ui_StartButton, 40);
    lv_obj_set_x(ui_StartButton, -80);
    lv_obj_set_y(ui_StartButton, 0);
    lv_obj_set_align(ui_StartButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StartButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_StartButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_StartButton, lv_color_hex(0xEEBE18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StartButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StartButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StartButton, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_StartButton, lv_color_hex(0xEEBE18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_StartButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_StartButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_StartButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StartLabel = lv_label_create(ui_StartButton);
    lv_obj_set_width(ui_StartLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StartLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_StartLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StartLabel, "START");
    lv_obj_set_style_text_color(ui_StartLabel, lv_color_hex(0xEEBE18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StartLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StartLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StopButton = lv_button_create(ui_Screen5);
    lv_obj_set_width(ui_StopButton, 65);
    lv_obj_set_height(ui_StopButton, 40);
    lv_obj_set_align(ui_StopButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StopButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_StopButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_StopButton, lv_color_hex(0xEEBE18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StopButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StopButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_StopButton, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_StopButton, lv_color_hex(0xEEBE18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_StopButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_StopButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_StopButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StopLabel = lv_label_create(ui_StopButton);
    lv_obj_set_width(ui_StopLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StopLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_StopLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StopLabel, "STOP");
    lv_obj_set_style_text_color(ui_StopLabel, lv_color_hex(0xEEBE18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StopLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StopLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ClearButton = lv_button_create(ui_Screen5);
    lv_obj_set_width(ui_ClearButton, 65);
    lv_obj_set_height(ui_ClearButton, 40);
    lv_obj_set_x(ui_ClearButton, 80);
    lv_obj_set_y(ui_ClearButton, 0);
    lv_obj_set_align(ui_ClearButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ClearButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ClearButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ClearButton, lv_color_hex(0xEEBE18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ClearButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ClearButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ClearButton, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ClearButton, lv_color_hex(0xEEBE18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ClearButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ClearButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ClearButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ClearLabel = lv_label_create(ui_ClearButton);
    lv_obj_set_width(ui_ClearLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ClearLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ClearLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ClearLabel, "CLEAR");
    lv_obj_set_style_text_color(ui_ClearLabel, lv_color_hex(0xEEBE18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ClearLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ClearLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimerLabel = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_TimerLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimerLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimerLabel, -3);
    lv_obj_set_y(ui_TimerLabel, 47);
    lv_obj_set_align(ui_TimerLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimerLabel, "00:00:00");
    lv_obj_set_style_text_color(ui_TimerLabel, lv_color_hex(0xEEBE18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimerLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_TimerLabel, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TimerLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TimerLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimerLabel, &ui_font_Bodon28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner1 = lv_spinner_create(ui_Screen5);
    //lv_spinner_set_anim_params(ui_Spinner1, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 25);
    lv_obj_set_height(ui_Spinner1, 25);
    lv_obj_set_x(ui_Spinner1, 121);
    lv_obj_set_y(ui_Spinner1, -99);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0xEEBE18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Spinner1, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_image_src(ui_Spinner1, &ui_img_1277287524, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_StartButton, ui_event_StartButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_StopButton, ui_event_StopButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ClearButton, ui_event_ClearButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen5, ui_event_Screen5, LV_EVENT_ALL, NULL);

}
