// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: Desktop_Effect_28_24

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Title1 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Title1, &ui_img_1_png);
    lv_obj_set_width(ui_Title1, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_Title1, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_Title1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Title1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Title1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TimeImage = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_TimeImage, &ui_img_1277292775);
    lv_obj_set_width(ui_TimeImage, LV_SIZE_CONTENT);   /// 38
    lv_obj_set_height(ui_TimeImage, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_TimeImage, -100);
    lv_obj_set_y(ui_TimeImage, -28);
    lv_obj_set_align(ui_TimeImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TimeImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_TimeImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DateImage = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_DateImage, &ui_img_195563596);
    lv_obj_set_width(ui_DateImage, LV_SIZE_CONTENT);   /// 35
    lv_obj_set_height(ui_DateImage, LV_SIZE_CONTENT);    /// 37
    lv_obj_set_x(ui_DateImage, -100);
    lv_obj_set_y(ui_DateImage, 46);
    lv_obj_set_align(ui_DateImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DateImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_DateImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TimeLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLabel, 30);
    lv_obj_set_y(ui_TimeLabel, -28);
    lv_obj_set_align(ui_TimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLabel, "18:30:29");
    lv_obj_set_style_text_color(ui_TimeLabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_TimeLabel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TimeLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TimeLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeLabel, &ui_font_Bodon28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TimeLabel, lv_color_hex(0x888789), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TimeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TimeLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_TimeLabel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TimeLabel, lv_color_hex(0xABA8AE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TimeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_TimeLabel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_TimeLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_TimeLabel, lv_color_hex(0x838183), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_TimeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_TimeLabel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_TimeLabel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_TimeLabel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_TimeLabel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TimeLabel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TimeLabel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TimeLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TimeLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_DateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DateLabel, 30);
    lv_obj_set_y(ui_DateLabel, 46);
    lv_obj_set_align(ui_DateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DateLabel, "2025-4-25");
    lv_obj_set_style_text_color(ui_DateLabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DateLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_DateLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_DateLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DateLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DateLabel, &ui_font_Bodon28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DateLabel, lv_color_hex(0x888789), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DateLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DateLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_DateLabel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_DateLabel, lv_color_hex(0xABA8AE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_DateLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_DateLabel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_DateLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_DateLabel, lv_color_hex(0x838183), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_DateLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_DateLabel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_DateLabel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_DateLabel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_DateLabel, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DateLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DateLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DateLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DateLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LocalImage = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_LocalImage, &ui_img_432210255);
    lv_obj_set_width(ui_LocalImage, LV_SIZE_CONTENT);   /// 21
    lv_obj_set_height(ui_LocalImage, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_x(ui_LocalImage, -68);
    lv_obj_set_y(ui_LocalImage, 100);
    lv_obj_set_align(ui_LocalImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LocalImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_LocalImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LocalLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LocalLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LocalLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LocalLabel, 12);
    lv_obj_set_y(ui_LocalLabel, 102);
    lv_obj_set_align(ui_LocalLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LocalLabel, "Shenzhen");
    lv_obj_set_style_text_font(ui_LocalLabel, &ui_font_ItaBodon22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
