// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: Desktop_Effect_28_24

#include "ui.h"

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Title6 = lv_image_create(ui_Screen6);
    lv_image_set_src(ui_Title6, &ui_img_6_png);
    lv_obj_set_width(ui_Title6, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_Title6, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_Title6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Title6, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Title6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnImage = lv_image_create(ui_Screen6);
    lv_image_set_src(ui_OnImage, &ui_img_126136084);
    lv_obj_set_width(ui_OnImage, LV_SIZE_CONTENT);   /// 43
    lv_obj_set_height(ui_OnImage, LV_SIZE_CONTENT);    /// 63
    lv_obj_set_x(ui_OnImage, -70);
    lv_obj_set_y(ui_OnImage, 0);
    lv_obj_set_align(ui_OnImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OnImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_OnImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OffImage = lv_image_create(ui_Screen6);
    lv_image_set_src(ui_OffImage, &ui_img_955593095);
    lv_obj_set_width(ui_OffImage, LV_SIZE_CONTENT);   /// 42
    lv_obj_set_height(ui_OffImage, LV_SIZE_CONTENT);    /// 63
    lv_obj_set_x(ui_OffImage, 70);
    lv_obj_set_y(ui_OffImage, 0);
    lv_obj_set_align(ui_OffImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OffImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_OffImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnButton = lv_button_create(ui_Screen6);
    lv_obj_set_width(ui_OnButton, 70);
    lv_obj_set_height(ui_OnButton, 40);
    lv_obj_set_x(ui_OnButton, -70);
    lv_obj_set_y(ui_OnButton, 78);
    lv_obj_set_align(ui_OnButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OnButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_OnButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OnButton, lv_color_hex(0xFFC208), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OnButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_OnButton, lv_color_hex(0xFFC208), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_OnButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_OnButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_OnButton, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_OnButton, lv_color_hex(0xFFC208), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_OnButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_OnButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_OnButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_OnButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_OnButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_OnButton);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "ON");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OffButton = lv_button_create(ui_Screen6);
    lv_obj_set_width(ui_OffButton, 70);
    lv_obj_set_height(ui_OffButton, 40);
    lv_obj_set_x(ui_OffButton, 68);
    lv_obj_set_y(ui_OffButton, 80);
    lv_obj_set_align(ui_OffButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OffButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_OffButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OffButton, lv_color_hex(0x9C9D9C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OffButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_OffButton, lv_color_hex(0x9C9D9C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_OffButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_OffButton, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_OffButton, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_OffButton, lv_color_hex(0x9C9D9C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_OffButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_OffButton, lv_color_hex(0xFFC208), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_OffButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_OffButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_OffButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_OffButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_OffButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_OffButton);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "ON");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_OnButton, ui_event_OnButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OffButton, ui_event_OffButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen6, ui_event_Screen6, LV_EVENT_ALL, NULL);

}
