// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: Desktop_Effect_28_24

#include "ui.h"

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Title4 = lv_image_create(ui_Screen4);
    lv_image_set_src(ui_Title4, &ui_img_4_png);
    lv_obj_set_width(ui_Title4, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_Title4, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_Title4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Title4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Title4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HourDropdown = lv_dropdown_create(ui_Screen4);
    lv_dropdown_set_options(ui_HourDropdown,
                            "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n\n");
    lv_obj_set_width(ui_HourDropdown, 76);
    lv_obj_set_height(ui_HourDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HourDropdown, -70);
    lv_obj_set_y(ui_HourDropdown, 20);
    lv_obj_set_align(ui_HourDropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HourDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_HourDropdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HourDropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_HourDropdown, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HourDropdown, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HourDropdown, lv_color_hex(0x294CB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HourDropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_HourDropdown, lv_color_hex(0x0008FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HourDropdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HourDropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HourDropdown, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_HourDropdown), lv_color_hex(0x808080),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_HourDropdown), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(lv_dropdown_get_list(ui_HourDropdown), 2,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(lv_dropdown_get_list(ui_HourDropdown), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_HourDropdown), &lv_font_montserrat_18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MinDropdown = lv_dropdown_create(ui_Screen4);
    lv_dropdown_set_options(ui_MinDropdown,
                            "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59");
    lv_obj_set_width(ui_MinDropdown, 76);
    lv_obj_set_height(ui_MinDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MinDropdown, 15);
    lv_obj_set_y(ui_MinDropdown, 20);
    lv_obj_set_align(ui_MinDropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MinDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_MinDropdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MinDropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_MinDropdown, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MinDropdown, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MinDropdown, lv_color_hex(0x294CB4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MinDropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_MinDropdown, lv_color_hex(0x0008FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MinDropdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MinDropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MinDropdown, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_MinDropdown), lv_color_hex(0x808080),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_MinDropdown), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(lv_dropdown_get_list(ui_MinDropdown), 2,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(lv_dropdown_get_list(ui_MinDropdown), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_MinDropdown), &lv_font_montserrat_18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HourAlarm = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_HourAlarm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HourAlarm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HourAlarm, -73);
    lv_obj_set_y(ui_HourAlarm, 65);
    lv_obj_set_align(ui_HourAlarm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HourAlarm, "Hour");
    lv_obj_set_style_text_color(ui_HourAlarm, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HourAlarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HourAlarm, &ui_font_ItaBodon16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MinAlarm = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_MinAlarm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MinAlarm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MinAlarm, 18);
    lv_obj_set_y(ui_MinAlarm, 65);
    lv_obj_set_align(ui_MinAlarm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MinAlarm, "Minute");
    lv_obj_set_style_text_color(ui_MinAlarm, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MinAlarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MinAlarm, &ui_font_ItaBodon16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ClockSwitch = lv_switch_create(ui_Screen4);
    lv_obj_set_width(ui_ClockSwitch, 50);
    lv_obj_set_height(ui_ClockSwitch, 27);
    lv_obj_set_x(ui_ClockSwitch, 85);
    lv_obj_set_y(ui_ClockSwitch, 22);
    lv_obj_set_align(ui_ClockSwitch, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ClockSwitch, lv_color_hex(0x6F758A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ClockSwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ClockSwitch, lv_color_hex(0xF6C600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ClockSwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ClockSwitch, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ClockSwitch, lv_color_hex(0xF6C600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ClockSwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ClockSwitch, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ClockSwitch, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ClockSwitch, lv_color_hex(0xF6C600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ClockSwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ClockSwitch, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ClockSwitch, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_ClockSwitch, lv_color_hex(0x294CB4), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ClockSwitch, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ClockSwitch, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ClockSwitch, lv_color_hex(0xF6C600), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ClockSwitch, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ClockSwitch, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ClockSwitch, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ClockSwitch, lv_color_hex(0xF6C600), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ClockSwitch, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ClockSwitch, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ClockSwitch, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ClockSwitch, lv_color_hex(0xF6C600), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ClockSwitch, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ClockSwitch, ui_event_ClockSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen4, ui_event_Screen4, LV_EVENT_ALL, NULL);

}
