// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: Desktop_Effect_35

#ifndef _DESKTOP_EFFECT_35_UI_H
#define _DESKTOP_EFFECT_35_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Title1;
extern lv_obj_t * ui_TimeLabel;
extern lv_obj_t * ui_DateLabel;
extern lv_obj_t * ui_LocalLabel;
extern lv_obj_t * ui_TimeImage;
extern lv_obj_t * ui_DateImage;
extern lv_obj_t * ui_LocalImage;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Title2;
extern lv_obj_t * ui_WeatherLabel;
extern lv_obj_t * ui_WeatherImage;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_TempLabel;
extern lv_obj_t * ui_WindLabel;
extern lv_obj_t * ui_HumiLabel;
extern lv_obj_t * ui_WindImage;
extern lv_obj_t * ui_TempImage;
extern lv_obj_t * ui_HumiImage;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Title3;
void ui_event_PlayOrPauseButton(lv_event_t * e);
extern lv_obj_t * ui_PlayOrPauseButton;
extern lv_obj_t * ui_PlayOrPauseLabel;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_SongNameLabel;
extern lv_obj_t * ui_MusicStatusLabel;
void ui_event_NextButton(lv_event_t * e);
extern lv_obj_t * ui_NextButton;
void ui_event_PreviousButton(lv_event_t * e);
extern lv_obj_t * ui_PreviousButton;
extern lv_obj_t * ui_MusicImage;
// CUSTOM VARIABLES

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
void ui_event_Screen4(lv_event_t * e);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Title4;
extern lv_obj_t * ui_HourDropdown;
extern lv_obj_t * ui_MinDropdown;
extern lv_obj_t * ui_HourAlarm;
extern lv_obj_t * ui_MinAlarm;
void ui_event_ClockSwitch(lv_event_t * e);
extern lv_obj_t * ui_ClockSwitch;
// CUSTOM VARIABLES

// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
void ui_event_Screen5(lv_event_t * e);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Title5;
void ui_event_StartButton(lv_event_t * e);
extern lv_obj_t * ui_StartButton;
extern lv_obj_t * ui_StartLabel;
void ui_event_StopButton(lv_event_t * e);
extern lv_obj_t * ui_StopButton;
extern lv_obj_t * ui_StopLabel;
void ui_event_ClearButton(lv_event_t * e);
extern lv_obj_t * ui_ClearButton;
extern lv_obj_t * ui_ClearLabel;
extern lv_obj_t * ui_TimerLabel;
extern lv_obj_t * ui_Spinner1;
// CUSTOM VARIABLES

// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
void ui_event_Screen6(lv_event_t * e);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_Title6;
extern lv_obj_t * ui_OnImage;
extern lv_obj_t * ui_OffImage;
void ui_event_OnButton(lv_event_t * e);
extern lv_obj_t * ui_OnButton;
extern lv_obj_t * ui_OnLabel;
void ui_event_OffButton(lv_event_t * e);
extern lv_obj_t * ui_OffButton;
extern lv_obj_t * ui_OffLabel;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1241096081);    // assets/背景01.png
LV_IMG_DECLARE(ui_img_1753269407);    // assets/桌面效果案例ui_11.png
LV_IMG_DECLARE(ui_img_149207794);    // assets/桌面效果案例ui_11 副本.png
LV_IMG_DECLARE(ui_img_1497549888);    // assets/桌面效果案例ui_11 副本 2.png
LV_IMG_DECLARE(ui_img_480x320_png);    // assets/480x320.png
LV_IMG_DECLARE(ui_img_2005372854);    // assets/桌面效果案例ui_11 副本 33.png
LV_IMG_DECLARE(ui_img_955595145);    // assets/桌面效果案例ui_11 副本 10.png
LV_IMG_DECLARE(ui_img_1497534778);    // assets/桌面效果案例ui_11 副本 8.png
LV_IMG_DECLARE(ui_img_1497535803);    // assets/桌面效果案例ui_11 副本 9.png
LV_IMG_DECLARE(ui_img_1241089683);    // assets/背景03.png
LV_IMG_DECLARE(ui_img_853450402);    // assets/下一首.png
LV_IMG_DECLARE(ui_img_862951715);    // assets/上一首.png
LV_IMG_DECLARE(ui_img_2005374904);    // assets/桌面效果案例ui_11 副本 13.png
LV_IMG_DECLARE(ui_img_1241099404);    // assets/背景04.png
LV_IMG_DECLARE(ui_img_1241100429);    // assets/背景05.png
LV_IMG_DECLARE(ui_img_1241093006);    // assets/背景06.png
LV_IMG_DECLARE(ui_img_1935945342);    // assets/桌面效果案例ui_11 副本 15.png
LV_IMG_DECLARE(ui_img_854216163);    // assets/桌面效果案例ui_11 副本 14.png

// FONTS
LV_FONT_DECLARE(ui_font_BodoniModaFont34);
LV_FONT_DECLARE(ui_font_ItaBodoniModaFont20);
LV_FONT_DECLARE(ui_font_ItaBodoniModaFont32);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
