// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: Desktop_Effect_35

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void PlayOrPauseSong(lv_event_t * e);
void NextSong(lv_event_t * e);
void PreviousSong(lv_event_t * e);
void AlarmClockSwitch(lv_event_t * e);
void Start_Timer(lv_event_t * e);
void Stop_Timer(lv_event_t * e);
void Clear_Timer(lv_event_t * e);
void Power_On(lv_event_t * e);
void Power_Off(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
