// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: Desktop_Effect

#ifdef __cplusplus     // C++ environment restrictions

#include "ui.h"
#include "Play_Music.h"
#include "Alarm_Clock.h"
#include "timer.h"
#include "Light_Control.h"

void PreviousSong(lv_event_t * e)
{
  	playPreviousSong();
}

void NextSong(lv_event_t * e)
{
  	playNextSong();
}

void PlayOrPauseSong(lv_event_t * e)
{
  	togglePlayPause();
}

void AlarmClockSwitch(lv_event_t * e) 
{
  	Turn_On_Off_Alarm();
}

void Start_Timer(lv_event_t * e)
{
	Activate_Timer();
}

void Stop_Timer(lv_event_t * e)
{
	Deactivate_Timer();
}

void Clear_Timer(lv_event_t * e)
{
	Reset_Timer();
}

void Power_On(lv_event_t * e)
{
	On_LED();
}

void Power_Off(lv_event_t * e)
{
	Off_LED();
}

#endif
