// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: Desktop_Effect_35

#include "ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Title2 = lv_image_create(ui_Screen2);
    lv_image_set_src(ui_Title2, &ui_img_480x320_png);
    lv_obj_set_width(ui_Title2, LV_SIZE_CONTENT);   /// 480
    lv_obj_set_height(ui_Title2, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_Title2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Title2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Title2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WeatherLabel = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_WeatherLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherLabel, 82);
    lv_obj_set_y(ui_WeatherLabel, 10);
    lv_obj_set_align(ui_WeatherLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeatherLabel, "Sunny");
    lv_obj_set_style_text_font(ui_WeatherLabel, &ui_font_ItaBodoniModaFont32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherImage = lv_image_create(ui_Screen2);
    lv_image_set_src(ui_WeatherImage, &ui_img_2005372854);
    lv_obj_set_width(ui_WeatherImage, LV_SIZE_CONTENT);   /// 150
    lv_obj_set_height(ui_WeatherImage, LV_SIZE_CONTENT);    /// 150
    lv_obj_set_x(ui_WeatherImage, -65);
    lv_obj_set_y(ui_WeatherImage, -17);
    lv_obj_set_align(ui_WeatherImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WeatherImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WeatherImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel1, 480);
    lv_obj_set_height(ui_Panel1, 90);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, 115);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x3159FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel1, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempLabel = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_TempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempLabel, -150);
    lv_obj_set_y(ui_TempLabel, 25);
    lv_obj_set_align(ui_TempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempLabel, "26");
    lv_obj_set_style_text_font(ui_TempLabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WindLabel = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_WindLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WindLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WindLabel, 150);
    lv_obj_set_y(ui_WindLabel, 25);
    lv_obj_set_align(ui_WindLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WindLabel, "3.0");
    lv_obj_set_style_text_font(ui_WindLabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumiLabel = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_HumiLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumiLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumiLabel, 0);
    lv_obj_set_y(ui_HumiLabel, 25);
    lv_obj_set_align(ui_HumiLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumiLabel, "50");
    lv_obj_set_style_text_font(ui_HumiLabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WindImage = lv_image_create(ui_Panel1);
    lv_image_set_src(ui_WindImage, &ui_img_955595145);
    lv_obj_set_width(ui_WindImage, LV_SIZE_CONTENT);   /// 35
    lv_obj_set_height(ui_WindImage, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_WindImage, 150);
    lv_obj_set_y(ui_WindImage, -15);
    lv_obj_set_align(ui_WindImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WindImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WindImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TempImage = lv_image_create(ui_Panel1);
    lv_image_set_src(ui_TempImage, &ui_img_1497534778);
    lv_obj_set_width(ui_TempImage, LV_SIZE_CONTENT);   /// 35
    lv_obj_set_height(ui_TempImage, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_TempImage, -150);
    lv_obj_set_y(ui_TempImage, -15);
    lv_obj_set_align(ui_TempImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TempImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_TempImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HumiImage = lv_image_create(ui_Panel1);
    lv_image_set_src(ui_HumiImage, &ui_img_1497535803);
    lv_obj_set_width(ui_HumiImage, LV_SIZE_CONTENT);   /// 33
    lv_obj_set_height(ui_HumiImage, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_HumiImage, 0);
    lv_obj_set_y(ui_HumiImage, -15);
    lv_obj_set_align(ui_HumiImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HumiImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_HumiImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}
